[package]
name = "gentle"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gentle"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
bio = "^1"
lazy_static = "^1"
csv = "^1"
itertools = "*"
# gb-io = "*" # Until nom-7 is merged and published
gb-io = { git = "https://github.com/dlesl/gb-io", branch = "nom-7" }
svg = "*"
anyhow = "*"
eframe = { version = "*", features = [
	"accesskit",
	"default_fonts",
	"glow",
	"wayland",
	# "web_screen_reader",
	"x11",
	"persistence",
] }
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "*", features = ["jpeg", "png"] }
rfd = "*"

[profile.release]
opt-level = 3
lto = 'fat'
panic = 'abort'
codegen-units = 1
strip = true
