[package]
name = "gentle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
bio = "^1"
lazy_static = "^1"
csv = "^1"
gb-io = "*"
svg = "*"
anyhow = "*"
eframe = { version = "*", features = [
	"accesskit",
	"default_fonts",
	"glow",
	"wayland",
	# "web_screen_reader",
	"x11",
	"persistence",
] }
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "*", features = ["jpeg", "png"] }
